# Generated by Django 4.1 on 2022-11-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
